name: 'build-test'
on:
  schedule:
    - cron: '* * * * *'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Update vscode-extensions.json
        run: |
          node ../../tools/vscode-extension-updater/lib/vscode-extension-updater.js ${{ secrets.GITHUB_TOKEN }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update vscode-extensions.json"
          git push origin master
